sudo: enabled

language: cpp

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - mkdir gtest
  - cd gtest
  - git clone https://github.com/google/googletest.git
  - cd googletest/googletest
  - export GTEST_DIR=$(pwd)
  - cd make
  - make
  - cd ../../../..

script:
  - ./configure --enable-gcov && make && make check
  - make clean
  - make
  - ./TicTacToeBoardTest

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'